// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhzM76S1DnnHgTgsifot7QbjJhVDlJfW4',
    appId: '1:793398910895:web:2cdf9ffeb7a43669b9595a',
    messagingSenderId: '793398910895',
    projectId: 'vegadelalyra-flutter-notes',
    authDomain: 'vegadelalyra-flutter-notes.firebaseapp.com',
    storageBucket: 'vegadelalyra-flutter-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBZfPEHvX1-AvkLOGuWGGpzK17S_LRMKk',
    appId: '1:793398910895:android:347cd5c477bba093b9595a',
    messagingSenderId: '793398910895',
    projectId: 'vegadelalyra-flutter-notes',
    storageBucket: 'vegadelalyra-flutter-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF0siF__bkEmxWrybJVBF0Am09yEv7hNY',
    appId: '1:793398910895:ios:99a6d1a3a73e38b3b9595a',
    messagingSenderId: '793398910895',
    projectId: 'vegadelalyra-flutter-notes',
    storageBucket: 'vegadelalyra-flutter-notes.appspot.com',
    iosBundleId: 'co.woldev.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF0siF__bkEmxWrybJVBF0Am09yEv7hNY',
    appId: '1:793398910895:ios:99a6d1a3a73e38b3b9595a',
    messagingSenderId: '793398910895',
    projectId: 'vegadelalyra-flutter-notes',
    storageBucket: 'vegadelalyra-flutter-notes.appspot.com',
    iosBundleId: 'co.woldev.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhzM76S1DnnHgTgsifot7QbjJhVDlJfW4',
    appId: '1:793398910895:web:ef9c7ec9dd15f8cfb9595a',
    messagingSenderId: '793398910895',
    projectId: 'vegadelalyra-flutter-notes',
    authDomain: 'vegadelalyra-flutter-notes.firebaseapp.com',
    storageBucket: 'vegadelalyra-flutter-notes.appspot.com',
  );
}
